### ISSUE TITLE
Retrofit instantiation shouldn't be done in AppModule

### ISSUE THREAD

**Issue by sleepylee** [prithivraj/Surveys#13]
https://github.com/prithivraj/Surveys/blob/master/app/src/main/java/com/zestworks/surveys/di/AppModule.kt
most likely in the real project we have the retrofit customized, shouldn't it be better to be placed in a proper manager class itself?

**Comment by prithivraj** [comment]
@sleepylee 

I think [this change](https://github.com/prithivraj/Surveys/pull/23/files/f0f430c09998fbea16749c89209b03564d8fe24d) can handle writable tokens. 
Thoughts?
